import Head from "next/head";
import Nav from "../components/Nav";
import { ThemeProvider } from "styled-components";
import { ResetStyle, GlobalStyle, COLOR } from "../styles/GlobalStyle";
import Works from "../components/Works";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900"
          rel="stylesheet"
        />
      </Head>
      <ThemeProvider theme={COLOR}>
        <ResetStyle />
        <GlobalStyle />
        <Nav />
        <Works />
      </ThemeProvider>
    </div>
  );
}
